version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
        - HUB_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    shm_size: 1gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub

  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: selenium-hub
    ports:
      - "4444:4444"